services:
  - type: web
    name: itexam-study-system
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile - src.web.app:app
    autoDeploy: true
    numReplicas: 1
    numDeploysToRetain: 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/database.db
      - key: SESSION_FILE_DIR
        value: /opt/render/project/src/flask_session
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health