services:
  - type: web
    name: itexam-study-system
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/database.db
    healthCheckPath: /health